source 'https://rubygems.org'

#ruby=2.1.1

# This is a gemset definition for RVM. If you don't want to use this specific
# gemset just delete the line. If RVM is not installed this line can be left,
# but will do nothing.
#ruby-gemset=pbssite

# Distribute your app as a gem
# gemspec

# Server requirements
gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'will_paginate', '~>3.0'
gem 'rack-coffee', :require => 'rack/coffee'
gem 'coffee-script'
gem 'sass'
gem 'slim'
gem 'mongoid', '~>3.0.0'
gem "will_paginate_mongoid", "~> 2.0.1"

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.12.0'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.12.0'
# end
